//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from KotlinConst.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class KotlinConstLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		CONST=1, VAL=2, DOUBLE=3, COLON=4, ASSIGN=5, SEMICOLON=6, MINUS=7, IDENT=8, 
		INT=9, REAL=10, WS=11, ERROR_CHAR=12;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"CONST", "VAL", "DOUBLE", "COLON", "ASSIGN", "SEMICOLON", "MINUS", "IDENT", 
		"INT", "REAL", "WS", "ERROR_CHAR"
	};


	public KotlinConstLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public KotlinConstLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'const'", "'val'", "'Double'", "':'", "'='", "';'", "'-'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "CONST", "VAL", "DOUBLE", "COLON", "ASSIGN", "SEMICOLON", "MINUS", 
		"IDENT", "INT", "REAL", "WS", "ERROR_CHAR"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "KotlinConst.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static KotlinConstLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static int[] _serializedATN = {
		4,0,12,82,6,-1,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,
		2,7,7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,1,0,1,0,1,0,1,0,1,0,1,0,1,
		1,1,1,1,1,1,1,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,3,1,3,1,4,1,4,1,5,1,5,1,6,
		1,6,1,7,1,7,5,7,53,8,7,10,7,12,7,56,9,7,1,8,4,8,59,8,8,11,8,12,8,60,1,
		9,4,9,64,8,9,11,9,12,9,65,1,9,1,9,4,9,70,8,9,11,9,12,9,71,1,10,4,10,75,
		8,10,11,10,12,10,76,1,10,1,10,1,11,1,11,0,0,12,1,1,3,2,5,3,7,4,9,5,11,
		6,13,7,15,8,17,9,19,10,21,11,23,12,1,0,4,3,0,65,90,95,95,97,122,4,0,48,
		57,65,90,95,95,97,122,1,0,48,57,3,0,9,10,13,13,32,32,86,0,1,1,0,0,0,0,
		3,1,0,0,0,0,5,1,0,0,0,0,7,1,0,0,0,0,9,1,0,0,0,0,11,1,0,0,0,0,13,1,0,0,
		0,0,15,1,0,0,0,0,17,1,0,0,0,0,19,1,0,0,0,0,21,1,0,0,0,0,23,1,0,0,0,1,25,
		1,0,0,0,3,31,1,0,0,0,5,35,1,0,0,0,7,42,1,0,0,0,9,44,1,0,0,0,11,46,1,0,
		0,0,13,48,1,0,0,0,15,50,1,0,0,0,17,58,1,0,0,0,19,63,1,0,0,0,21,74,1,0,
		0,0,23,80,1,0,0,0,25,26,5,99,0,0,26,27,5,111,0,0,27,28,5,110,0,0,28,29,
		5,115,0,0,29,30,5,116,0,0,30,2,1,0,0,0,31,32,5,118,0,0,32,33,5,97,0,0,
		33,34,5,108,0,0,34,4,1,0,0,0,35,36,5,68,0,0,36,37,5,111,0,0,37,38,5,117,
		0,0,38,39,5,98,0,0,39,40,5,108,0,0,40,41,5,101,0,0,41,6,1,0,0,0,42,43,
		5,58,0,0,43,8,1,0,0,0,44,45,5,61,0,0,45,10,1,0,0,0,46,47,5,59,0,0,47,12,
		1,0,0,0,48,49,5,45,0,0,49,14,1,0,0,0,50,54,7,0,0,0,51,53,7,1,0,0,52,51,
		1,0,0,0,53,56,1,0,0,0,54,52,1,0,0,0,54,55,1,0,0,0,55,16,1,0,0,0,56,54,
		1,0,0,0,57,59,7,2,0,0,58,57,1,0,0,0,59,60,1,0,0,0,60,58,1,0,0,0,60,61,
		1,0,0,0,61,18,1,0,0,0,62,64,7,2,0,0,63,62,1,0,0,0,64,65,1,0,0,0,65,63,
		1,0,0,0,65,66,1,0,0,0,66,67,1,0,0,0,67,69,5,46,0,0,68,70,7,2,0,0,69,68,
		1,0,0,0,70,71,1,0,0,0,71,69,1,0,0,0,71,72,1,0,0,0,72,20,1,0,0,0,73,75,
		7,3,0,0,74,73,1,0,0,0,75,76,1,0,0,0,76,74,1,0,0,0,76,77,1,0,0,0,77,78,
		1,0,0,0,78,79,6,10,0,0,79,22,1,0,0,0,80,81,9,0,0,0,81,24,1,0,0,0,6,0,54,
		60,65,71,76,1,6,0,0
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
